### ISSUE TITLE
Elm components not being rendered during production build

### ISSUE THREAD

**Issue by ethagnawl** [wking-io/gatsby-plugin-elm#1]
First off, thanks for putting this plugin together. I was not expecting it to be so easy to get an Elm program integrated into a Gatsby application.

I have run into one snag, though. When I build my Gatsby application, the contents of my Elm application are missing.

Case in point:

```
// page.js
export default ({ data }) => {
  let scenes = [{some: 'thing'}];
  return (
    <>
    <h1>hi</h1>
    <MyComponent scenes={scenes} />
    </>
  )
} 
```

```
// index.html
<h1>hi</h1><div></div></div></div>
```

Is this behavior to be expected? I have a sinking feeling that this is a limitation of Elm and/or the underlying plugins.

**Comment by wking-io** [comment]
How are you initializing the elm runtime into your React application?

**Comment by ethagnawl** [comment]
[Here's](https://gist.github.com/ethagnawl/1e1bdbbfcdeda0fb264fa81d7bd5bef0) a contrived example which demonstrates how I'm initializing Elm and produces the unexpected results. (FWIW, I took inspiration from [this](https://github.com/reify-academy/reify-academy-website) repository.)

Also, just to be clear, the Elm app is behaving as expected at runtime, it's just that its contents are missing in the pre-rendered, static HTML files.

**Comment by wking-io** [comment]
Thanks for the links! So I haven't had a chance to double check, but I am pretty sure the reason you are running into issues is that you are using a function component in React. This means that your component is always going to re-render (controlled by React) every time the parent re-renders. This will then wipe all DOM that was generated when you initialized your Elm app. On top of that Elm will have no idea this happened and not know it needs to re-initialize. 

To handle Elm within React since Elm is a separate Virtual DOM and therefore manages items own DOM updates you want to use a Class Component so that you can use the shouldComponentUpdate lifecycle method to make sure that the initialized Elm runtime never gets wiped. 

I have a version of an ElmHandler component I use in the new `elm-live` Docs site you can use as reference. I am hoping to open source this ElmHandler as well and would love your feedback as well if you use it!

*ElmHandler:* https://github.com/wking-io/elm-live/blob/www/www/src/components/elm-handler.js

*In Use:* https://github.com/wking-io/elm-live/blob/4ae831d7bf9540e7682ce82e8bc13fbf31cbcaec/www/src/components/documentation.js#L165


*Ports:* https://github.com/wking-io/elm-live/blob/www/www/src/lib/ports.js

It's not documented very well since it is still WIP so let me know if you have any Qs!

Note: I am using a JS version of Either (Result in Elm) which makes for the syntax in the port function. You can also pass props of any type

**Comment by ethagnawl** [comment]
Thank you for all of the above. I will try to modify my demo and report back.

**Comment by ethagnawl** [comment]
I've reworked my example to use your `ElmHandler` (the only difference is that I removed the call to `getOrElse`) and extended `React.Component` when creating my page component, but I'm still seeing the same behavior. I also tried moving the parameterized (flag) values into the Elm application's model on the off chance that that was the hangup, but that didn't change anything.

Here are the relevant pieces of my revamped demo: https://gist.github.com/ethagnawl/a12ed9cd030b5f3045c56d20d4215097

I think I'm going to have to abandon this attempt at smuggling Elm into this Gatsby app, so please feel free to close this issue. If your demo is working, I think the likely cause is end-user error on my part -- I purposely put off learning React, in favor of Elm, and my lack of knowledge is likely the cause of this issue. Either way, your plugin seems to be working as it should.

**Comment by wking-io** [comment]
I will confirm on my project that it works when running the production build and if so then I will close otherwise I may have missed something! 👍

**Comment by wking-io** [comment]
@ethagnawl okay I built mine out using production bundle and it worked. One thing I had an error with is that the only way you can view your production build locally is using the command `gatsby serve`. Are you using that to preview the production build?

**Comment by ethagnawl** [comment]
Arg. Well, I guess that sort of confirms my suspicions about the problem being on my end. Were you building the elm-live repo in your tests? If so, I'll try to do that when I have a minute.

> Are you using that to preview the production build?

I was running `gatsby build` and then using cat/grep to search for the expected values in public/index.html.

**Comment by wking-io** [comment]
Oh, yeah you are probably not going to see it that way. Elm will still be loaded as a separate JS file I believe and will still need to be initialized. So I would recommend running `gatsby build && gatsby serve` then checkout the page. :)

**Comment by ethagnawl** [comment]
> Elm will still be loaded as a separate JS file I believe and will still need to be initialized.

Ah, yeah ... that's what I was afraid of. I just want to confirm, though: you're saying the contents of the Elm app _won't ever_ be rendered server side during the Gatsby build process? I tried to emphasize this in my [earlier comments](https://github.com/wking-io/gatsby-plugin-elm/issues/1#issuecomment-448087188), but I may not have been explicit enough.

**Comment by wking-io** [comment]
Ahhhhhh....yeah it will not be Server Side rendered. Gatsby has no idea how to manage that with Elm and also Elm has no idea how to do that with elm lol. 🤣 

I just built this because a part of my application didn't matter if it was SSR but had more complex logic than I wanted to do in React, but it also had a lot of content I wanted to be SEO optimized and SSR. So, best of both worlds so far. hah
